# Generated by Django 3.1.6 on 2021-02-18 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('brand', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marca')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Rating')),
                ('numReviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='Num. reviews')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Precio')),
                ('countInStock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category', models.ManyToManyField(to='base.Category', verbose_name='Categorias')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['createdAt', 'rating', 'price', 'countInStock'],
            },
        ),
    ]
