# Generated by Django 3.1.6 on 2021-02-19 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20210217_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('paymentMethod', models.CharField(blank=True, max_length=200, null=True, verbose_name='Metodo de pago')),
                ('taxtPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Impuesto')),
                ('shippingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Costo de envio')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Descuento')),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Precio total')),
                ('isPaid', models.BooleanField(default=False, verbose_name='Pagado')),
                ('paidAt', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('isDelivered', models.BooleanField(default=False, verbose_name='Entregado')),
                ('deliveredAT', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'ordering': ['createdAt', '_id'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAdress',
            fields=[
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio ')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad')),
                ('postalCode', models.CharField(blank=True, max_length=200, null=True, verbose_name='Codigo Postal')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='País')),
                ('shippingPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Costo de envio')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
            options={
                'verbose_name': 'Domicilio de envio',
                'verbose_name_plural': 'Domicilios de envio',
                'ordering': ['_id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Rating')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['createdAt', 'rating'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('qty', models.IntegerField(blank=True, default=0, null=True, verbose_name='cantidad')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Precio')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.product')),
            ],
            options={
                'verbose_name': 'Orden item',
                'verbose_name_plural': 'Orden items',
                'ordering': ['_id'],
            },
        ),
    ]
