# Generated by Django 3.1.6 on 2021-02-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_coupon_porcentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='porcentage',
            new_name='percentage',
        ),
    ]
