# Generated by Django 3.1.6 on 2021-02-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_product_out_of_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/product_images/placeholder.png', null=True, upload_to='product_images/', verbose_name='imagen'),
        ),
    ]
