# Generated by Django 3.1.6 on 2021-03-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20210228_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='stripe_product_id'),
        ),
    ]
