# Generated by Django 3.1.6 on 2021-03-02 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_auto_20210301_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStripe',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(max_length=100, verbose_name='Nombre')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User-stripe-id',
                'verbose_name_plural': 'User-stripe-ids',
                'ordering': ['_id'],
            },
        ),
    ]
