# Generated by Django 3.1.7 on 2021-03-02 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_userstripe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstripe',
            name='stripe_customer_id',
            field=models.CharField(max_length=100, verbose_name='stripe customer id'),
        ),
        migrations.CreateModel(
            name='UserPaymentMethodsStripe',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_id', models.CharField(max_length=100, verbose_name='stripe ')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User-payment-method-stripe-id',
                'verbose_name_plural': 'User-payment-method-stripe-ids',
                'ordering': ['_id'],
            },
        ),
    ]
