# Generated by Django 3.1.7 on 2021-03-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20210302_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='default',
            field=models.BooleanField(default=True, verbose_name='default'),
        ),
        migrations.AlterField(
            model_name='userpaymentmethodsstripe',
            name='default',
            field=models.BooleanField(default=True, verbose_name='default'),
        ),
    ]
