# Generated by Django 3.1.6 on 2021-02-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210218_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orderitems_images/', verbose_name='imagen'),
        ),
    ]
