# Generated by Django 3.1.6 on 2021-02-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210225_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='receiver_first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Recibidor primer nombre '),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='receiver_last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Recibidor apellidos'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Porcentaje'),
        ),
    ]
