# Generated by Django 3.1.6 on 2021-02-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_coupon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Código'),
        ),
    ]
