# Generated by Django 3.1.6 on 2021-03-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_orderitem_stripe_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='stripe_product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='stripe_product_id'),
        ),
    ]
