# Generated by Django 3.1.7 on 2021-03-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_shippingadress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='default',
            field=models.BooleanField(default=False, verbose_name='default'),
        ),
        migrations.AddField(
            model_name='userpaymentmethodsstripe',
            name='default',
            field=models.BooleanField(default=False, verbose_name='default'),
        ),
    ]
